fix: failed to make due to const
Running 'cmake .. && make' failed with error
...
/home/jj/antlr/Tester/include/dtl/Diff.hpp:166:27: error: assignment of member ‘trivial’ in read-only object
  166 |             this->trivial = true;
      |             ~~~~~~~~~~~~~~^~~~~~
make[2]: *** [src/tests/CMakeFiles/tests.dir/build.make:76: src/tests/CMakeFiles/tests.dir/TestRunning.cpp.o] Error 1
...

Don't know much about C++ but it seems like declaring this method as
const prevents the class from altering its field.
Removing const from the method declaration lets me compile it with make.